[package]
name = "conver"
version = "0.1.0"
authors = ["Devin Alvaro <devin.alvaro@gmail.com>"]
edition = "2018"

[dependencies]
bincode = "1.1.4"
clap = "2.33.0"
redis = "0.11.0"
serde = { version = "1.0.92", features = ["derive"] }

[dev-dependencies]
lazy_static = "1.3.0"
rand = "0.6.5"
