[package]
name = "point"
version = "0.1.0"
authors = ["Devin Alvaro <devin.alvaro@gmail.com>"]
edition = "2018"

[dependencies]
bincode = "1.1.4"
serde = { version = "1.0.92", features = ["derive"] }
